name: Convert to PDF

on:
  push:
    branches:
      -     yasamansaffarii.github.io

 # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Pandoc
      run: |
        sudo apt-get install -y pandoc

    - name: Convert to PDF
      run: |
        pandoc yasamansaffarii.github.io/CV.md -o path/to/your/output.pdfyasamansaffarii.github.io/CV.pdf
